### PR TITLE
fix: Playwright 0.11.0+ support

### LINKED ISSUE #33: Migrate to new playwright version
[Playwright 0.11.0](https://github.com/microsoft/playwright/releases/tag/v0.11.0) was released, as I know there were some changes with API, so it can need some changes to current implementation
#30

### PR DESCRIPTION
**Pull request by mxschmitt**
- fix: that the standalone exports are now the same like the normal `playwright` package (https://github.com/microsoft/playwright/pull/818)
- fix: dependencies should not be in `optionalDependencies` and `devDependencies` at the same time. NPM logged for that a warning. So I've adjusted it. But not 100% sure if it's correct like that. Providing versions for them is in my mind a good idea.

```
npm WARN The package jest-dev-server is included as both a dev and production dependency.
npm WARN The package playwright is included as both a dev and production dependency.
```

Closes #33 

(It wasn't working with the 0.11+ version when the standalone version was used.)

```
TypeError: playwrightInstance.launch is not a function
```

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -46,11 +46,11 @@
     "jest-environment-node": "^25.1.0"
   },
   "optionalDependencies": {
-    "jest-dev-server": "*",
```
Comment (mxschmitt) [inline package.json]: Is this an optional dependency? feels like it's a `devDependency`.

Comment (mmarkelov) [reply package.json]: @mxschmitt I think it should be optional, cause we need it if only **server** option defined in config

Comment (mxschmitt) [reply package.json]: ah yep, I agree! :)

File: src/utils.js [hunk 2]
```diff
@@ -53,7 +53,8 @@ export async function readPackage() {
   const packageConfig = await require(absConfigPath)
   const playwright =
     checkDependencies(packageConfig.dependencies) ||
-    checkDependencies(packageConfig.devDependencies)
+    checkDependencies(packageConfig.devDependencies) ||
+    checkDependencies(packageConfig.optionalDependencies)
```
Comment (mmarkelov) [inline src/utils.js]: I'm not sure that we need to checkout **optionalDependencies**

Comment (mxschmitt) [reply src/utils.js]: the other option would be to simply return "playwright" if packageConfig.name === "jest-playwright-preset". Because without that the tests are failing

Comment (mmarkelov) [reply src/utils.js]: @mxschmitt oh! now I see we need it to pass tests. Yeah! We need to find out some workaround it

File: src/utils.js [hunk 3]
```diff
@@ -62,12 +66,9 @@ export async function readPackage() {
 
 export async function getPlaywrightInstance(browserType) {
   const playwrightPackage = await readPackage()
-  if (playwrightPackage === 'playwright') {
```
Comment (mmarkelov) [inline src/utils.js]: I'm not quit sure that it wiil be ok, if we are using `playwright-firefox` for example, and then we will run tests without browser definition, that's ok for now, but now it will throw an error, i suppose, cause `chromium` will be default value. So we need some extra logic to find out using version

Comment (mxschmitt) [reply src/utils.js]: we = jest tests in this repo?

yep lets maybe figure out a better way later if we want to test the individual configurations.
Tests are fixed now with this workaround.

Comment (mmarkelov) [reply src/utils.js]: @mxschmitt no. It will crash for other users with it configuration:
**package.json**
```json
...
"scripts": {
    "test": "jest"
  },
"dependencies": {
    "jest-playwright-preset": "0.0.9",
    "playwright-firefox": "^0.11.0"
  },
...
```

With **0.10.0** running `test` will be fine, but with **0.11.0** it will crash I suppose, if browser not be defined. So it need to be `BROWSER=firefox test` as example

Comment (mmarkelov) [reply src/utils.js]: I can check it out and just add some extra logic in this PR

Comment (mxschmitt) [reply src/utils.js]: would be awesome, thanks
